// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: book_event.sql

package db

import (
	"context"
	"time"
)

const bookEvent = `-- name: BookEvent :one

SELECT id, book_id, "action", timestamp, created_at, updated_at
FROM book_events
WHERE id = ?1
LIMIT 1
`

func (q *Queries) BookEvent(ctx context.Context, id int64) (BookEvent, error) {
	row := q.db.QueryRowContext(ctx, bookEvent, id)
	var i BookEvent
	err := row.Scan(
		&i.ID,
		&i.BookID,
		&i.Action,
		&i.Timestamp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const bookEvents = `-- name: BookEvents :many

SELECT id, book_id, "action", timestamp, created_at, updated_at
FROM book_events
ORDER BY id
`

func (q *Queries) BookEvents(ctx context.Context) ([]BookEvent, error) {
	rows, err := q.db.QueryContext(ctx, bookEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BookEvent
	for rows.Next() {
		var i BookEvent
		if err := rows.Scan(
			&i.ID,
			&i.BookID,
			&i.Action,
			&i.Timestamp,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const bookEventsByBookID = `-- name: BookEventsByBookID :many

SELECT id, book_id, "action", timestamp, created_at, updated_at
FROM book_events
WHERE book_id = ?1
ORDER BY timestamp DESC
`

func (q *Queries) BookEventsByBookID(ctx context.Context, bookID int64) ([]BookEvent, error) {
	rows, err := q.db.QueryContext(ctx, bookEventsByBookID, bookID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BookEvent
	for rows.Next() {
		var i BookEvent
		if err := rows.Scan(
			&i.ID,
			&i.BookID,
			&i.Action,
			&i.Timestamp,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const checkOutLog = `-- name: CheckOutLog :many

SELECT books.title,
    books.author,
    books.isbn,
    book_events.action,
    book_events.timestamp
FROM book_events
    INNER JOIN books ON book_events.book_id = books.id
ORDER BY book_events.timestamp DESC
`

type CheckOutLogRow struct {
	Title     string    `json:"title"`
	Author    string    `json:"author"`
	Isbn      string    `json:"isbn"`
	Action    string    `json:"action"`
	Timestamp time.Time `json:"timestamp"`
}

func (q *Queries) CheckOutLog(ctx context.Context) ([]CheckOutLogRow, error) {
	rows, err := q.db.QueryContext(ctx, checkOutLog)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CheckOutLogRow
	for rows.Next() {
		var i CheckOutLogRow
		if err := rows.Scan(
			&i.Title,
			&i.Author,
			&i.Isbn,
			&i.Action,
			&i.Timestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createBookEvent = `-- name: CreateBookEvent :one
INSERT INTO book_events (book_id, action, timestamp)
VALUES (?1, ?2, ?3)
RETURNING id, book_id, "action", timestamp, created_at, updated_at
`

type CreateBookEventParams struct {
	BookID    int64     `json:"book_id"`
	Action    string    `json:"action"`
	Timestamp time.Time `json:"timestamp"`
}

func (q *Queries) CreateBookEvent(ctx context.Context, arg CreateBookEventParams) (BookEvent, error) {
	row := q.db.QueryRowContext(ctx, createBookEvent, arg.BookID, arg.Action, arg.Timestamp)
	var i BookEvent
	err := row.Scan(
		&i.ID,
		&i.BookID,
		&i.Action,
		&i.Timestamp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBookEvent = `-- name: DeleteBookEvent :one

DELETE FROM book_events
WHERE id = ?1
RETURNING id, book_id, "action", timestamp, created_at, updated_at
`

func (q *Queries) DeleteBookEvent(ctx context.Context, id int64) (BookEvent, error) {
	row := q.db.QueryRowContext(ctx, deleteBookEvent, id)
	var i BookEvent
	err := row.Scan(
		&i.ID,
		&i.BookID,
		&i.Action,
		&i.Timestamp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBookEvent = `-- name: UpdateBookEvent :one

UPDATE book_events
SET book_id = (
        CASE
            WHEN CAST(?3 AS integer) != 0 THEN ?3
            ELSE book_id
        END
    ),
    action = (
        CASE
            WHEN CAST(?4 AS text) != '' THEN ?4
            ELSE action
        END
    ),
    timestamp = (
        CASE
            WHEN CAST(?5 AS bool) THEN ?2
            ELSE timestamp
        END
    ),
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?1
RETURNING id, book_id, "action", timestamp, created_at, updated_at
`

type UpdateBookEventParams struct {
	ID                    int64     `json:"id"`
	Timestamp             time.Time `json:"timestamp"`
	BookID                int64     `json:"book_id"`
	Action                string    `json:"action"`
	ShouldUpdateTimestamp bool      `json:"should_update_timestamp"`
}

func (q *Queries) UpdateBookEvent(ctx context.Context, arg UpdateBookEventParams) (BookEvent, error) {
	row := q.db.QueryRowContext(ctx, updateBookEvent,
		arg.ID,
		arg.Timestamp,
		arg.BookID,
		arg.Action,
		arg.ShouldUpdateTimestamp,
	)
	var i BookEvent
	err := row.Scan(
		&i.ID,
		&i.BookID,
		&i.Action,
		&i.Timestamp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
