// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: book.sql

package db

import (
	"context"
	"database/sql"
)

const archiveBook = `-- name: ArchiveBook :one

UPDATE books
SET archived_at = ?2
WHERE id = ?1
RETURNING id, isbn, title, author, description, checked_out_at, created_at, updated_at, archived_at
`

type ArchiveBookParams struct {
	ID         int64        `json:"id"`
	ArchivedAt sql.NullTime `json:"archived_at"`
}

func (q *Queries) ArchiveBook(ctx context.Context, arg ArchiveBookParams) (Book, error) {
	row := q.db.QueryRowContext(ctx, archiveBook, arg.ID, arg.ArchivedAt)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Isbn,
		&i.Title,
		&i.Author,
		&i.Description,
		&i.CheckedOutAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const book = `-- name: Book :one

SELECT id, isbn, title, author, description, checked_out_at, created_at, updated_at, archived_at
FROM books
WHERE id = ?1
LIMIT 1
`

func (q *Queries) Book(ctx context.Context, id int64) (Book, error) {
	row := q.db.QueryRowContext(ctx, book, id)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Isbn,
		&i.Title,
		&i.Author,
		&i.Description,
		&i.CheckedOutAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const books = `-- name: Books :many

SELECT id, isbn, title, author, description, checked_out_at, created_at, updated_at, archived_at
FROM books
WHERE archived_at IS NULL
ORDER BY id
`

func (q *Queries) Books(ctx context.Context) ([]Book, error) {
	rows, err := q.db.QueryContext(ctx, books)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Book
	for rows.Next() {
		var i Book
		if err := rows.Scan(
			&i.ID,
			&i.Isbn,
			&i.Title,
			&i.Author,
			&i.Description,
			&i.CheckedOutAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const checkInBook = `-- name: CheckInBook :one

UPDATE books
SET checked_out_at = NULL
WHERE id = ?1
RETURNING id, isbn, title, author, description, checked_out_at, created_at, updated_at, archived_at
`

func (q *Queries) CheckInBook(ctx context.Context, id int64) (Book, error) {
	row := q.db.QueryRowContext(ctx, checkInBook, id)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Isbn,
		&i.Title,
		&i.Author,
		&i.Description,
		&i.CheckedOutAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const checkOutBook = `-- name: CheckOutBook :one

UPDATE books
SET checked_out_at = ?2
WHERE id = ?1
RETURNING id, isbn, title, author, description, checked_out_at, created_at, updated_at, archived_at
`

type CheckOutBookParams struct {
	ID           int64        `json:"id"`
	CheckedOutAt sql.NullTime `json:"checked_out_at"`
}

func (q *Queries) CheckOutBook(ctx context.Context, arg CheckOutBookParams) (Book, error) {
	row := q.db.QueryRowContext(ctx, checkOutBook, arg.ID, arg.CheckedOutAt)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Isbn,
		&i.Title,
		&i.Author,
		&i.Description,
		&i.CheckedOutAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const createBook = `-- name: CreateBook :one
INSERT INTO books (
        isbn,
        title,
        author,
        description,
        checked_out_at,
        archived_at
    )
VALUES (?1, ?2, ?3, ?4, ?5, ?6)
RETURNING id, isbn, title, author, description, checked_out_at, created_at, updated_at, archived_at
`

type CreateBookParams struct {
	Isbn         string         `json:"isbn"`
	Title        string         `json:"title"`
	Author       string         `json:"author"`
	Description  sql.NullString `json:"description"`
	CheckedOutAt sql.NullTime   `json:"checked_out_at"`
	ArchivedAt   sql.NullTime   `json:"archived_at"`
}

func (q *Queries) CreateBook(ctx context.Context, arg CreateBookParams) (Book, error) {
	row := q.db.QueryRowContext(ctx, createBook,
		arg.Isbn,
		arg.Title,
		arg.Author,
		arg.Description,
		arg.CheckedOutAt,
		arg.ArchivedAt,
	)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Isbn,
		&i.Title,
		&i.Author,
		&i.Description,
		&i.CheckedOutAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const deleteBook = `-- name: DeleteBook :one

DELETE FROM books
WHERE id = ?1
RETURNING id, isbn, title, author, description, checked_out_at, created_at, updated_at, archived_at
`

func (q *Queries) DeleteBook(ctx context.Context, id int64) (Book, error) {
	row := q.db.QueryRowContext(ctx, deleteBook, id)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Isbn,
		&i.Title,
		&i.Author,
		&i.Description,
		&i.CheckedOutAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const updateBook = `-- name: UpdateBook :one

UPDATE books
SET isbn = (
        CASE
            WHEN CAST(?2 AS text) != '' THEN ?2
            ELSE isbn
        END
    ),
    title = (
        CASE
            WHEN CAST(?3 AS text) != '' THEN ?3
            ELSE title
        END
    ),
    author = (
        CASE
            WHEN CAST(?4 AS text) != '' THEN ?4
            ELSE author
        END
    ),
    description = (
        CASE
            WHEN CAST(?5 AS text) != '' THEN ?5
            ELSE description
        END
    ),
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?1
RETURNING id, isbn, title, author, description, checked_out_at, created_at, updated_at, archived_at
`

type UpdateBookParams struct {
	ID          int64  `json:"id"`
	Isbn        string `json:"isbn"`
	Title       string `json:"title"`
	Author      string `json:"author"`
	Description string `json:"description"`
}

func (q *Queries) UpdateBook(ctx context.Context, arg UpdateBookParams) (Book, error) {
	row := q.db.QueryRowContext(ctx, updateBook,
		arg.ID,
		arg.Isbn,
		arg.Title,
		arg.Author,
		arg.Description,
	)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Isbn,
		&i.Title,
		&i.Author,
		&i.Description,
		&i.CheckedOutAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}
