// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"
)

type Book struct {
	ID           int64          `json:"id"`
	Isbn         string         `json:"isbn"`
	Title        string         `json:"title"`
	Author       string         `json:"author"`
	Description  sql.NullString `json:"description"`
	CheckedOutAt sql.NullTime   `json:"checked_out_at"`
	CreatedAt    time.Time      `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
	ArchivedAt   sql.NullTime   `json:"archived_at"`
}

type BookEvent struct {
	ID        int64     `json:"id"`
	BookID    int64     `json:"book_id"`
	Action    string    `json:"action"`
	Timestamp time.Time `json:"timestamp"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}
